# Generated by Django 3.1.5 on 2021-01-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='address2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
