# Generated by Django 3.1.5 on 2021-02-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='name',
            field=models.CharField(default=True, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='part_no',
            field=models.CharField(default=True, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='stock',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='vendor',
            field=models.CharField(default=True, max_length=256),
            preserve_default=False,
        ),
    ]
