# Generated by Django 3.1.5 on 2021-02-06 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210206_0039'),
        ('part', '0002_auto_20210205_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='account',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountcompany'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
    ]
