# Generated by Django 3.1.5 on 2021-02-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210214_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcompany',
            name='membership',
            field=models.CharField(choices=[('Pro', 'Pro'), ('Basic', 'Basic'), ('Enterprise', 'Enterprise')], default='Basic', max_length=254),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='role',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Admin', 'Admin')], default='Tech', max_length=20, null=True),
        ),
    ]
