# Generated by Django 3.1.5 on 2021-02-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210216_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcompany',
            name='membership',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Enterprise', 'Enterprise'), ('Pro', 'Pro')], default='Basic', max_length=254),
        ),
    ]
