# Generated by Django 3.1.5 on 2021-01-21 07:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvided',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountcompany')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('scope', models.TextField()),
                ('repair_notes', models.TextField(blank=True)),
                ('additional_work', models.TextField()),
                ('schedule', models.DateField(default=datetime.date.today)),
                ('start_job', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountcompany')),
                ('assigned', models.ManyToManyField(blank=True, to='accounts.AccountUser')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.serviceprovided')),
                ('t_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('t_jobsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.jobsite')),
                ('t_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.tickettype')),
            ],
        ),
    ]
