# Generated by Django 3.1.5 on 2021-01-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20210123_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='stop',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('LUNCH', 'LUNCH')], default='1st', max_length=254),
        ),
    ]
