# Generated by Django 3.1.5 on 2021-01-29 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20210129_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='schedule',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
