# Generated by Django 3.1.5 on 2021-02-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_auto_20210205_2349'),
        ('ticket', '0011_auto_20210202_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='parts_used',
            field=models.ManyToManyField(blank=True, to='part.Part'),
        ),
    ]
