# Generated by Django 3.1.5 on 2021-02-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_ticket_parts_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='parts_used',
        ),
    ]
