# Generated by Django 3.1.5 on 2021-02-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_auto_20210209_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='parts_used',
        ),
    ]
